abstract: add color codes for mIRC compatible client
author: HIROSE Masaaki  C<< <hirose31@gmail.com> >>
build_requires: 
  Test::Base: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: String-IRC
no_index: 
  directory: 
    - inc
    - t
version: 0.02
